#!/bin/bash

# Script and comment art below made by JetLaggedEgg (me).
# http://github.com/jetlaggedegg/make-me-a-sandwich

# Credit to Nate from http://www.ascii-art.de/ascii/s/sandwich.txt for sandiwch ascii art.
# I intend no copyright infringment and am not selling or asking for donations. I am simply
# sharing this script, which I made for personal use, with people of the world.

#
#
#     Make me a sandwich.
#             |
#             |             What? Make
#             |            it yourself.
#             |                 |
#       Sudo make me            |
#        a sandwich.            |
#             |                 |
#             \               Okay.
#              \                \
#              |_                \   _
#           _ /   \                /   \
#          /  \__/                 \_ /
#         |   \||                   /|\
#         |    \\_\________        | ||
#         |     |__\_______\         |
#         |         \      |\       /\
#         |_______________/ |      |  \
#         O               O |      |  |

if [ "$(whoami)" != "root" ]; then
  echo "What? Make it yourself."
else
  echo -n "Okay."
  echo -n "."
  sleep 1
  echo -n "."
  sleep 1
  echo -n "."
  sleep 1
  cat << "EOF"
                   _.---._
                _.-~       ~-._
            _.-~               ~-._
        _.-~                       ~---._
    _.-~                                 ~\
 .-~                                    _.;
 :-._                               _.-~ ./
 `-._~-._                   _..__.-~ _.-~
  /  ~-._~-._              / .__..--~----._
 \_____(_;-._\.        _.-~_/       ~).. . \
    /(_____  \`--...--~_.-~______..-+_______)
  .(_________/`--...--~/    _/nad        /\
 /-._     \_     (___./_..-~__.....__..-~./
 `-._~-._   ~\--------~  .-~_..__.-~ _.-~
     ~-._~-._ ~---------'  / .__..--~
         ~-._\.        _.-~_/
             \`--...--~_.-~
              `--...--~
EOF
fi
